#pragma once

#define LAYER_STATE_32BIT
#define FORCE_NKRO
#define PERMISSIVE_HOLD
#define TAP_CODE_DELAY 50
#define UNICODE_SELECTED_MODES UNICODE_MODE_LINUX, UNICODE_MODE_WINCOMPOSE
#define UNICODE_CYCLE_PERSIST FALSE
#define UNICODE_TYPE_DELAY 2
#define BOTH_SHIFTS_TURNS_ON_CAPS_WORD
#define MOONLANDER_USER_LEDS

