LTO_ENABLE = yes

NKRO_ENABLE = yes
EXTRAKEY_ENABLE = yes
MOUSEKEY_ENABLE = yes
UNICODEMAP_ENABLE = yes
STENO_ENABLE = yes
CAPS_WORD_ENABLE = yes
SPACE_CADET_ENABLE = yes

GRAVE_ESC_ENABLE = no
TAP_DANCE_ENABLE = no
CONSOLE_ENABLE = no
COMMAND_ENABLE = no
MAGIC_ENABLE = no

